### ISSUE TITLE
command line flag --in keyfile.txt in batch_trim_se.pl doesn't work

### ISSUE THREAD

**Issue by relshire** [Lanilen/GBS-PreProcess#1]
When:

batch_trim_se.pl -h it says:
Usage: /home/debian/bin/batch_trim_se.pl [parameters] --in input_keyfile

--in does not work, but -i does.

Cheers!

**Comment by Lanilen** [comment]
Hm, they were meant to be synonymous, but you're right, it doesn't seem to be working. I'll change the help docs to -i and look into the synonymous flags later on. Thanks!
